# This file controls the configuration for the "Dependabot" service, used to keep dependencies updated.
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# See the above link for the reason why "directory" is set to "/"
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"

  # npm dependencies (JavaScript/TypeScript ecosystem)
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      # Group ESLint, TypeScript, and TypeScript ESLint dependencies to avoid peer dependency conflicts
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "typescript"
        update-types:
          - "major"
          - "minor"
          - "patch"
      # Group Jest-related dependencies to maintain compatibility
      jest:
        patterns:
          - "jest"
          - "jest-*"
          - "@types/jest"
          - "ts-jest"
        update-types:
          - "major"
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "typescript"
          - "jest"
          - "jest-*"
          - "@types/jest"
          - "ts-jest"
        update-types:
          - "minor"
          - "patch"
