# This file controls the configuration for the "Dependabot" service, used to keep dependencies updated.
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# See the above link for the reason why "directory" is set to "/"
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"

  # npm dependencies (JavaScript/TypeScript ecosystem)
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "javascript"
    # Group development dependencies together
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "prettier"
          - "@typescript-eslint/*"
          - "jest"
          - "vitest"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
