coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 5%
        if_not_found: success
      generators:
        target: 70%
        threshold: 3%
        paths:
          - src/generators/
        if_not_found: success
    patch:
      default:
        target: 60%
        threshold: 5%
        if_not_found: success

flags:
  unittests:
    paths:
      - src/
    carryforward: false

comment:
  layout: "header,diff,flags,components,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "dist/"
  - "coverage/"
  - "benchmarks/"
  - "tools/"
  - "test/"
  - "test-results/"
  - "**/*.d.ts"
  - "**/*.test.ts"
  - "**/*.bench.ts"
  - "src/cli.ts"
  - "src/logging/pino-pretty-transport.js"

github_checks:
  annotations: true
