coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 5%
        if_not_found: success
    patch:
      default:
        target: 60%
        threshold: 5%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

test_analytics:
  # Enable test analytics notifications for PR visibility
  notifications:
    - type: github_status
      context: "codecov/test-analytics"
    - type: github_check
      name: "Codecov Test Analytics"

  # Configure flaky test detection
  flaky_detection:
    enabled: true
    threshold: 0.1 # Mark tests as flaky if they fail 10% of the time

ignore:
  - "dist/"
  - "coverage/"
  - "benchmarks/"
  - "tools/"
  - "test/"
  - "**/*.d.ts"
  - "src/cli.ts"
