name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is. Screenshots are helpful for UI issues!
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior. Screenshots can be very helpful here!
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: foundry-version
    attributes:
      label: FoundryVTT Version
      description: What version of FoundryVTT are you running?
      placeholder: e.g., v11.315
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: What version of Woodland Generators are you using?
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: |
        Open browser Developer Tools (F12 or right-click → Inspect), go to Console tab.
        Look for red error messages when the issue occurs. Include the full error with stack trace if available.
        Tip: You can right-click on error messages to "Copy" the full details.
      placeholder: |
        Example:
        Error: Cannot read property 'generate' of undefined
            at Object.generateCharacter (module.js:42:15)
            at HTMLButtonElement.onclick (index.html:123:5)
