name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is. Include any error messages or unexpected output.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior. Include the exact commands you ran.
      placeholder: |
        1. Run command `woodland-gen character --faction bird`
        2. Select option '...'
        3. See error
    validations:
      required: true

  - type: input
    id: cli-version
    attributes:
      label: CLI Version
      description: What version of Woodland Generators CLI are you using? (Run `woodland-gen --version` to check)
      placeholder: e.g., v0.1.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you running? (Run `node --version` to check)
      placeholder: e.g., v18.17.0
    validations:
      required: true

  - type: input
    id: os-info
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 13.4, Ubuntu 22.04
    validations:
      required: true
