name: Dependencies

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "package.json"
      - "package-lock.json"
      - ".pre-commit-config.yaml"
      - ".github/workflows/deps.yml"

jobs:
  unused:
    name: Check unused
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for unused dependencies
        run: npm run check:deps

  security:
    name: Security audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Security audit
        run: npm run check:audit

  sync-precommit:
    name: Sync pre-commit dependencies
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      !contains(github.event.head_commit.author.name, 'woodland-generators[bot]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Sync pre-commit dependencies
        run: npm run sync:deps

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.has-changes == 'true'
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "woodland-generators[bot]"
          git add .pre-commit-config.yaml
          git commit -m "[woodland-generators[bot]] sync dependencies with package.json"
          git push
