name: Dependencies

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/deps.yml"

jobs:
  unused:
    name: Check unused
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check for unused dependencies
        run: npm run check:deps

  security:
    name: Security audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Security audit
        run: npm run check:audit
