name: Environment Validation

on:
  push:
    paths:
      - ".vscode/extensions.json"
      - ".devcontainer/devcontainer.json"
      - ".github/workflows/environment.yml"
      - "scripts/validate-workspace.ts"
  pull_request:
    paths:
      - ".vscode/extensions.json"
      - ".devcontainer/devcontainer.json"
      - ".github/workflows/environment.yml"
      - "scripts/validate-workspace.ts"

jobs:
  validate-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Validate workspace configuration
        run: npm run check:workspace
