name: PR Testing Instructions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-testing-info:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add PR testing comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: testing-instructions
          message: |
            ## 🧪 Testing Instructions

            This pull request can be tested directly in FoundryVTT.

            ### Quick Install

            Copy this URL and paste it into FoundryVTT's "Install Module" dialog:

            ```
            https://raw.githubusercontent.com/${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}/module.json
            ```

            ### Testing Steps

            1. **Open FoundryVTT** and go to **Setup** → **Add-on Modules**
            2. **Click "Install Module"**
            3. **Paste the URL above** into the "Manifest URL" field
            4. **Click "Install"** to install this PR version
            5. **Create or open a test world** (don't use your main worlds for testing!)
            6. **Enable the module** in the world's module settings
            7. **Test the changes** described in this PR

            ### What to Test

            Please test:
            - ✅ Module installs and enables without errors
            - ✅ Core functionality works as expected
            - ✅ No console errors (check browser developer tools)
            - ✅ Changes work as described in the PR description

            ---
            *This comment was automatically generated. The testing URL will update automatically when new commits are pushed to this PR.*
