name: pre-commit

# This workflow runs all pre-commit hooks with proper environment setup
# including manual installation of tools that aren't available in pre-commit.ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install lychee
        run: ./tools/install-lychee.sh

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: pre-commit/action@v3.0.1
